server.port=8080

spring.config.import=optional:file:.env
openai.api.key=${OPENAI_API_KEY}

naver.client.id=${naver.client.id}
naver.client.secret=${naver.client.secret}

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.fervijwxdgkwjtcpzskx&password=3U2OyISOn7AcNRT6

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect